title: Icicles of Thought
subtitle: Notes on Software Craftsmanship, Web Development & Distributed Systems
description: ''
keywords: null
author: Lorefnon
language: en
timezone: Asia/Kolkata
root: /
permalink: ':title/'
permalink_defaults:
  lang: en
pretty_urls:
  trailing_index: false
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':year/:month/:day/:title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: /blog
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: experimental
deploy:
  type: ''
cli_renderer:
  - executable: sass
    streamInput: false
    sourceExtensions:
      - sass
      - scss
    targetExtension: css
    args:
      - '--load-path=node_modules'
      - '--load-path=themes/experimental/source/css'
      - '--style=compressed'
      - '{{{filePath}}}'
marked:
  gfm: true
  pedantic: false
  breaks: false
  smartLists: true
  smartypants: false
  quotes: “”‘’
  modifyAnchors: 0
  anchorAlias: false
  autolink: true
  mangle: true
  sanitizeUrl: false
  headerIds: true
  lazyload: true
  prependRoot: false
  postAsset: false
  external_link:
    enable: true
    exclude: []
    nofollow: true
  disableNunjucks: false
  descriptionLists: false
feed:
  enable: true
  limit: 10
url: https://lorefnon.me
